steps:
  - name: 'Build Docker Image'
    dockerfile: Dockerfile
    image: 'gcr.io/$PROJECT_ID/image-editor-backend:$SHORT_SHA'

  - name: 'Push Docker Image to GCR'
    waitFor: ['Build Docker Image']
    push:
      - 'gcr.io/$PROJECT_ID/image-editor-backend:$SHORT_SHA'

  - name: 'Initialize Terraform'
    waitFor: ['Push Docker Image to GCR']
    entrypoint: 'terraform'
    args: ['init']

  - name: 'Apply Terraform'
    waitFor: ['Initialize Terraform']
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve', '-var', "backend_image=gcr.io/$PROJECT_ID/image-editor-backend:$SHORT_SHA"]
    env:
      - TF_VAR_project_id=$PROJECT_ID
      - TF_VAR_region=${_CLOUD_RUN_REGION}
      - TF_VAR_gcr_region=${_GCR_REGION} # If you use it in Terraform
      - TF_VAR_backend_service_name=${_BACKEND_SERVICE_NAME} # If you use it in Terraform
      - TF_VAR_container_port=${_CONTAINER_PORT} # If you use it in Terraform