name: Backend CI/CD with Cloud Build and Terraform

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }} # Or use workload identity

      - name: Build and Deploy with Cloud Build and Terraform
        run: |
          gcloud builds submit --config cloudbuild.yaml \
            --substitutions=_CLOUD_RUN_REGION=${{ vars.CLOUD_RUN_REGION }},\
            _GCR_REGION=${{ vars.GCR_REGION }},\
            _BACKEND_SERVICE_NAME=${{ vars.BACKEND_SERVICE_NAME }},\
            _CONTAINER_PORT=${{ vars.CONTAINER_PORT }} \
            .