name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main] # Or your main development branch (e.g., master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read # Explicitly set even if workflow-level is different
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build React app
        run: cd frontend && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch GitHub Pages will deploy from
          folder: frontend/build # The folder containing your built site